# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Karma - Fitness and Health
email: jay@karma.net
description: >- # this means to ignore newlines until "baseurl:"
  Diagnosed with pancreas cancer (Distal Cholangiocarcinoma to be exact) on August 23rd, 2018. 
  I had the <a href="/2018/09/12/surgery-complete">Whipple</a> procedure to remove the tumor and nodes affected on September 11th, 2018. 
  Kickin' Pancreas cancer in the dick ever since.
permalink: :year/:month/:day/:title
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jcolson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jcolson
github_username:  jcolson

# Build settings
theme: jekyll-theme-dinky
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
    category:
        output: true
  
defaults:
    -
        scope:
            path: ""
            type: category
        values:
            layout: "category"
